# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    blog_service:
        class: AppBundle\Service\BlogService
        calls:
            - [setContainer, ["@service_container"]]
    blog_repo:
        class: AppBundle\Repository\BlogRepository
        factory: ['@doctrine', getRepository]
        arguments:
            - 'AppBundle:Blog'
    redis:
        class: AppBundle\Service\RedisService
        arguments:
            - '@snc_redis.default'